"""
init_db.py
----------
Initializes all database tables and seeds minimal bootstrap data.
Full production seed data is generated by database/seed.py.

Supports both SQLite (local dev) and PostgreSQL (Supabase cloud).

Tables:
  departments · users · employees · incidents · tickets
  knowledge_articles · audit_logs · agent_events · tool_executions
  workflow_results · long_term_memory · notifications
"""

import os
import sys
import json

# Ensure parent directory is in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database.connection import db_manager

# Backward-compat aliases
INCIDENTS_DB = db_manager._db_path
TICKETS_DB   = db_manager._db_path
MEMORY_DB    = db_manager._db_path

# ---------------------------------------------------------------------------
# DDL — ordered by dependency (parents before children)
# ---------------------------------------------------------------------------
_TABLES = [

    # 1. Departments
    """CREATE TABLE IF NOT EXISTS departments (
        id         INTEGER PRIMARY KEY AUTOINCREMENT,
        name       TEXT NOT NULL UNIQUE,
        manager_id TEXT,
        created_at TEXT NOT NULL
    )""",

    # 2. Users (auth table — minimal, used by JWT)
    """CREATE TABLE IF NOT EXISTS users (
        username    TEXT PRIMARY KEY,
        name        TEXT NOT NULL,
        role        TEXT NOT NULL,
        employee_id TEXT NOT NULL,
        email       TEXT NOT NULL,
        password    TEXT NOT NULL
    )""",

    # 3. Employees (extended HR profile)
    """CREATE TABLE IF NOT EXISTS employees (
        employee_id   TEXT PRIMARY KEY,
        name          TEXT NOT NULL,
        email         TEXT NOT NULL,
        department    TEXT,
        title         TEXT,
        manager       TEXT,
        phone         TEXT,
        location      TEXT,
        hire_date     TEXT,
        is_vip        INTEGER DEFAULT 0,
        created_at    TEXT NOT NULL
    )""",

    # 4. Incidents (extended)
    """CREATE TABLE IF NOT EXISTS incidents (
        incident_id         TEXT PRIMARY KEY,
        incident_number     TEXT UNIQUE,
        employee_id         TEXT NOT NULL,
        employee_name       TEXT,
        issue               TEXT NOT NULL,
        category            TEXT,
        subcategory         TEXT,
        priority            TEXT DEFAULT 'Medium',
        severity            TEXT,
        confidence          REAL,
        status              TEXT NOT NULL,
        assigned_to         TEXT,
        assigned_team       TEXT,
        resolution          TEXT,
        resolution_strategy TEXT,
        ticket_number       TEXT,
        requires_approval   INTEGER DEFAULT 0,
        approval_action     TEXT,
        approval_reason     TEXT,
        approval_status     TEXT DEFAULT 'N/A',
        created_at          TEXT NOT NULL,
        updated_at          TEXT NOT NULL,
        resolved_at         TEXT
    )""",

    # 5. Tickets
    """CREATE TABLE IF NOT EXISTS tickets (
        ticket_id    TEXT PRIMARY KEY,
        ticket_number TEXT UNIQUE,
        incident_id  TEXT,
        "user"       TEXT,
        issue        TEXT,
        priority     TEXT,
        status       TEXT,
        assigned_team TEXT,
        created_at   TEXT,
        updated_at   TEXT
    )""",

    # 6. Knowledge Articles
    """CREATE TABLE IF NOT EXISTS knowledge_articles (
        id             INTEGER PRIMARY KEY AUTOINCREMENT,
        article_number TEXT NOT NULL UNIQUE,
        title          TEXT NOT NULL,
        category       TEXT NOT NULL,
        subcategory    TEXT,
        content        TEXT NOT NULL,
        resolution     TEXT,
        severity       TEXT,
        approved       INTEGER DEFAULT 1,
        views          INTEGER DEFAULT 0,
        created_at     TEXT NOT NULL,
        updated_at     TEXT NOT NULL
    )""",

    # 7. Audit Logs
    """CREATE TABLE IF NOT EXISTS audit_logs (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        incident_id     TEXT NOT NULL,
        timestamp       TEXT NOT NULL,
        agent_or_system TEXT NOT NULL,
        event_type      TEXT NOT NULL,
        description     TEXT NOT NULL,
        payload         TEXT
    )""",

    # 8. Agent Events
    """CREATE TABLE IF NOT EXISTS agent_events (
        id         INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id TEXT,
        publisher  TEXT,
        event_type TEXT,
        payload    TEXT,
        timestamp  TEXT
    )""",

    # 9. Tool Executions
    """CREATE TABLE IF NOT EXISTS tool_executions (
        id         INTEGER PRIMARY KEY AUTOINCREMENT,
        tool_name  TEXT,
        success    INTEGER,
        error      TEXT,
        latency_ms REAL,
        args       TEXT,
        result     TEXT,
        timestamp  TEXT
    )""",

    # 10. Workflow Results
    """CREATE TABLE IF NOT EXISTS workflow_results (
        incident_id TEXT PRIMARY KEY,
        session_id  TEXT,
        query       TEXT,
        plan        TEXT,
        research    TEXT,
        analysis    TEXT,
        decision    TEXT,
        status      TEXT,
        answer      TEXT,
        timings     TEXT,
        created_at  TEXT
    )""",

    # 11. Long-term Memory
    """CREATE TABLE IF NOT EXISTS long_term_memory (
        key        TEXT PRIMARY KEY,
        value      TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )""",

    # 12. Notifications
    """CREATE TABLE IF NOT EXISTS notifications (
        id           INTEGER PRIMARY KEY AUTOINCREMENT,
        incident_id  TEXT,
        recipient    TEXT NOT NULL,
        channel      TEXT DEFAULT 'email',
        status       TEXT DEFAULT 'sent',
        message      TEXT NOT NULL,
        sent_at      TEXT NOT NULL
    )""",
]

# ---------------------------------------------------------------------------
# Bootstrap seed data (minimal — full data comes from database/seed.py)
# ---------------------------------------------------------------------------
_BOOTSTRAP_USERS = [
    ("emp1024",   "Akhil Gouda",          "Employee",   "EMP1024", "akhil@company.com",   "password123"),
    ("itsupport", "Alex Morgan (IT Lead)", "IT Support", "EMP8080", "support@enterprise.com", "support123"),
    ("admin",     "System Administrator", "Admin",      "EMP0001", "admin@enterprise.com",   "admin123"),
]

_BOOTSTRAP_DEPTS = [
    ("Engineering",    None),
    ("IT",             None),
    ("Human Resources",None),
    ("Finance",        None),
    ("Operations",     None),
    ("Sales",          None),
    ("Marketing",      None),
    ("Legal",          None),
    ("Customer Success",None),
    ("Executive",      None),
]

_BOOTSTRAP_INCIDENTS = [
    (
        "INC-1020","INC-1020","EMP1024","Akhil Gouda",
        "VPN dropped after Windows update",
        "Network","VPN","High","Medium",92.0,"AUTO-RESOLUTION",
        "IT Auto-Bot","Network Team","Reset VPN adapter and reinstall VPN profile.","Auto-Fix",
        "TKT-0001",0,None,None,"N/A",
        "2026-08-10T10:00:00Z","2026-08-10T10:02:00Z","2026-08-10T10:02:30Z"
    ),
    (
        "INC-1021","INC-1021","EMP1025","Sarah Johnson",
        "Printer spooler offline in HR floor",
        "Hardware","Printer","Low","Low",88.0,"AUTO-RESOLUTION",
        "IT Auto-Bot","Hardware Team","Restarted spooler service.","Auto-Fix",
        "TKT-0002",0,None,None,"N/A",
        "2026-08-10T11:15:00Z","2026-08-10T11:16:00Z","2026-08-10T11:16:30Z"
    ),
    (
        "INC-1022","INC-1022","EMP1026","David Chen",
        "Disable active directory account due to breach",
        "Security","Account Access","Critical","High",75.0,"PENDING_APPROVAL",
        "IT Support","Security Team",None,"Escalate",
        "TKT-0003",1,"Disable User Account EMP1026","Security incident flag","PENDING",
        "2026-08-10T12:30:00Z","2026-08-10T12:30:00Z",None
    ),
    (
        "INC-1023","INC-1023","EMP1027","Elena Rodriguez",
        "Outlook email relay bounce 5.7.1",
        "Email","SMTP Relay","Medium","Medium",82.0,"INVESTIGATING",
        "Tier-2 IT","Email Team",None,"Escalate",
        "TKT-0004",0,None,None,"N/A",
        "2026-08-10T13:40:00Z","2026-08-10T14:00:00Z",None
    ),
    (
        "INC-1024","INC-1024","EMP1024","Akhil Gouda",
        "WiFi disconnected in conference room B",
        "Network","WiFi","Low","Low",95.0,"RESOLVED",
        "IT Auto-Bot","Network Team","Flushed DNS and reconnected.","Auto-Fix",
        "TKT-0005",0,None,None,"N/A",
        "2026-08-10T14:10:00Z","2026-08-10T14:12:00Z","2026-08-10T14:12:00Z"
    ),
]

_BOOTSTRAP_MEMORIES = [
    ("EMP1024_history", json.dumps({
        "employee_name": "Akhil Gouda", "department": "Engineering",
        "previous_incidents": ["VPN connection timeout","WiFi disconnect","Printer offline"],
        "successful_resolutions": {
            "VPN": "Reset network adapter MTU to 1400",
            "WiFi": "Flush DNS and reconnect"
        },
        "vip_status": True
    }), "2026-08-10T10:00:00Z"),
    ("EMP1025_history", json.dumps({
        "employee_name": "Sarah Johnson", "department": "Human Resources",
        "previous_incidents": ["Password expired","Outlook OST sync"],
        "successful_resolutions": {"Password": "SSPR portal link reset"},
        "vip_status": False
    }), "2026-08-10T10:00:00Z"),
    ("vpn_resolution_knowledge", json.dumps({
        "pattern": "VPN connection failure after Windows update",
        "root_cause": "Windows update modifies network adapter settings, breaking VPN tunnel",
        "resolution": "Reset VPN adapter: netsh int ip reset. Reinstall VPN profile.",
        "confidence": 92,
        "verified": True
    }), "2026-08-10T10:00:00Z"),
]

_BOOTSTRAP_KB = [
    (
        "KB-0001","VPN Connection Failure After Windows Update",
        "Network","VPN",
        "Windows updates often modify network stack settings causing VPN client to lose connectivity. "
        "Common symptoms: VPN client shows connected but no traffic passes, or fails to authenticate.",
        "1. Open cmd as Admin. 2. Run: netsh int ip reset. 3. Run: netsh winsock reset. "
        "4. Reinstall VPN profile from IT portal. 5. Reboot and test.",
        "Medium",1,
        "2026-08-01T00:00:00Z","2026-08-01T00:00:00Z"
    ),
    (
        "KB-0002","Outlook Cannot Connect to Exchange Server",
        "Email","Exchange",
        "Outlook shows 'Disconnected' or 'Trying to connect' for extended periods. "
        "May be caused by expired credentials, corrupted profile, or server-side issue.",
        "1. Check Outlook status bar — if showing 'Need Password', re-enter credentials. "
        "2. Delete and recreate Outlook profile via Control Panel > Mail. "
        "3. Run: outlook.exe /cleanprofile. 4. If persists, contact IT — may be server issue.",
        "Medium",1,
        "2026-08-01T00:00:00Z","2026-08-01T00:00:00Z"
    ),
    (
        "KB-0003","Password Reset via SSPR Portal",
        "Security","Account Access",
        "Employees can reset their own password using the Self-Service Password Reset (SSPR) portal "
        "without contacting IT support.",
        "1. Navigate to: https://sspr.enterprise.local. 2. Enter employee email. "
        "3. Verify identity via SMS/Authenticator app. 4. Set new password meeting policy requirements. "
        "5. Allow 5 minutes for AD replication before logging in.",
        "Low",1,
        "2026-08-01T00:00:00Z","2026-08-01T00:00:00Z"
    ),
]


def _migrate_schema():
    """Ensure all required columns exist on tables (works for both SQLite and PostgreSQL)."""
    migrations = {
        "incidents": {
            "incident_number": "TEXT",
            "subcategory": "TEXT",
            "priority": "TEXT DEFAULT 'Medium'",
            "assigned_team": "TEXT",
            "resolution": "TEXT",
            "resolution_strategy": "TEXT",
            "resolution_steps": "TEXT",
            "resolution_attempt_count": "INTEGER DEFAULT 0",
            "user_confirmed_resolution": "INTEGER DEFAULT 0",
            "resolution_confirmed_at": "TEXT",
            "escalation_reason": "TEXT",
            "ticket_id": "TEXT",
            "last_resolution_attempt": "TEXT",
            "resolution_time_hours": "REAL",
            "ticket_number": "TEXT",
            "resolved_at": "TEXT",
        },
        "tickets": {
            "ticket_number": "TEXT",
            "incident_id": "TEXT",
            "assigned_team": "TEXT",
        },
        "audit_logs": {
            "payload": "TEXT",
        },
        "notifications": {
            "message": "TEXT",
            "channel": "TEXT DEFAULT 'email'",
            "subject": "TEXT",
        }
    }

    is_postgres = db_manager.is_postgres
    for table, cols in migrations.items():
        try:
            if is_postgres:
                rows = db_manager.fetchall(
                    f"SELECT column_name FROM information_schema.columns WHERE table_name = '{table}'"
                )
                existing = {r["column_name"] for r in rows}
            else:
                rows = db_manager.fetchall(f"PRAGMA table_info({table})")
                existing = {r["name"] for r in rows}

            for col_name, col_type in cols.items():
                if col_name not in existing and existing:
                    try:
                        db_manager.execute(f"ALTER TABLE {table} ADD COLUMN {col_name} {col_type}")
                    except Exception as err:
                        if "already exists" not in str(err).lower() and "duplicate" not in str(err).lower():
                            print(f"[!] Migration notice ({table}.{col_name}): {err}")
        except Exception as e:
            pass


# ---------------------------------------------------------------------------
# Main initializer
# ---------------------------------------------------------------------------
def init_databases():
    """Create all tables and seed bootstrap data (idempotent)."""

    # 1. Create all tables
    for ddl in _TABLES:
        try:
            db_manager.execute(ddl, ddl=True)
        except Exception as err:
            print(f"[!] Table creation warning (may already exist): {err}")

    # 2. Run column migrations for existing SQLite / Postgres tables
    _migrate_schema()

    now = "2026-08-01T00:00:00Z"

    # 2. Seed departments
    try:
        count = db_manager.fetchone("SELECT COUNT(*) AS c FROM departments")
        if not count or int(count.get("c", 0)) == 0:
            for dept_name, mgr in _BOOTSTRAP_DEPTS:
                db_manager.execute(
                    "INSERT INTO departments (name, manager_id, created_at) "
                    "VALUES (?,?,?) ON CONFLICT(name) DO NOTHING",
                    (dept_name, mgr, now)
                )
            print("[*] Seeded departments table.")
    except Exception as e:
        print(f"[!] departments seed warning: {e}")

    # 3. Seed users & demo employee profile
    try:
        for u in _BOOTSTRAP_USERS:
            db_manager.execute(
                "INSERT INTO users (username,name,role,employee_id,email,password) "
                "VALUES (?,?,?,?,?,?) ON CONFLICT(username) DO UPDATE SET name=EXCLUDED.name, email=EXCLUDED.email",
                u
            )
        # Always ensure EMP1024 employee HR record exists with requested details
        db_manager.execute(
            "INSERT INTO employees (employee_id,name,email,department,title,manager,phone,location,hire_date,is_vip,created_at) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(employee_id) DO UPDATE SET "
            "name=EXCLUDED.name, email=EXCLUDED.email, manager=EXCLUDED.manager, location=EXCLUDED.location, department=EXCLUDED.department",
            ("EMP1024", "Akhil Gouda", "akhil@company.com", "Engineering", "Software Engineer", "Karthik", "+91 98765 43210", "Hyderabad", "2024-01-15", 1, now)
        )
        print("[*] Seeded/updated users and demo employee table.")
    except Exception as e:
        print(f"[!] users seed warning: {e}")

    # 4. Seed incidents
    try:
        count = db_manager.fetchone("SELECT COUNT(*) AS c FROM incidents")
        if not count or int(count.get("c", 0)) == 0:
            for inc in _BOOTSTRAP_INCIDENTS:
                db_manager.execute(
                    "INSERT INTO incidents "
                    "(incident_id,incident_number,employee_id,employee_name,issue,category,subcategory,"
                    "priority,severity,confidence,status,assigned_to,assigned_team,resolution,"
                    "resolution_strategy,ticket_number,requires_approval,approval_action,"
                    "approval_reason,approval_status,created_at,updated_at,resolved_at) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
                    "ON CONFLICT(incident_id) DO NOTHING",
                    inc
                )
            print("[*] Seeded incidents table.")
    except Exception as e:
        print(f"[!] incidents seed warning: {e}")

    # 5. Seed long-term memory
    try:
        count = db_manager.fetchone("SELECT COUNT(*) AS c FROM long_term_memory")
        if not count or int(count.get("c", 0)) == 0:
            for m in _BOOTSTRAP_MEMORIES:
                db_manager.execute(
                    "INSERT INTO long_term_memory (key,value,updated_at) "
                    "VALUES (?,?,?) ON CONFLICT(key) DO NOTHING",
                    m
                )
            print("[*] Seeded long_term_memory table.")
    except Exception as e:
        print(f"[!] memory seed warning: {e}")

    # 6. Seed bootstrap knowledge articles
    try:
        count = db_manager.fetchone("SELECT COUNT(*) AS c FROM knowledge_articles")
        if not count or int(count.get("c", 0)) == 0:
            for kb in _BOOTSTRAP_KB:
                db_manager.execute(
                    "INSERT INTO knowledge_articles "
                    "(article_number,title,category,subcategory,content,resolution,severity,approved,created_at,updated_at) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(article_number) DO NOTHING",
                    kb
                )
            print("[*] Seeded knowledge_articles table.")
    except Exception as e:
        print(f"[!] knowledge_articles seed warning: {e}")

    print("[*] Database initialization complete.")


if __name__ == "__main__":
    init_databases()
